# Generated by Django 2.1.3 on 2018-11-07 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceleration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mph', models.PositiveSmallIntegerField(verbose_name='mph')),
                ('seconds', models.FloatField(verbose_name='seconds')),
                ('manufacturer', models.TextField(verbose_name='manufacturer')),
                ('model', models.TextField(verbose_name='manufacturer')),
                ('activation_code', models.TextField(verbose_name='activationCode')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.TextField(verbose_name='ownerName')),
                ('serial_number', models.PositiveSmallIntegerField(verbose_name='serialNumber')),
                ('model_year', models.BigIntegerField(verbose_name='modelYear')),
                ('code', models.TextField(verbose_name='code')),
                ('vehicle_code', models.TextField(verbose_name='vehicleCode')),
                ('acceleration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.Acceleration', verbose_name='acceleration')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(verbose_name='capacity')),
                ('num_cylinders', models.PositiveSmallIntegerField(verbose_name='numCylinders')),
                ('max_rpm', models.PositiveIntegerField(verbose_name='maxRpm')),
                ('manufacturer_code', models.CharField(max_length=1, verbose_name='manufacturerCode')),
            ],
        ),
        migrations.CreateModel(
            name='FuelFigures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveIntegerField(verbose_name='speed')),
                ('mpg', models.FloatField(verbose_name='mpg')),
                ('usage_description', models.PositiveSmallIntegerField(verbose_name='usageDescription')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceFigures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('octane_rating', models.PositiveSmallIntegerField(verbose_name='octaneRating')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.Engine', verbose_name='engine'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_figures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.FuelFigures', verbose_name='fuelFigures'),
        ),
        migrations.AddField(
            model_name='car',
            name='performance_figures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.PerformanceFigures', verbose_name='performanceFigures'),
        ),
    ]
